// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBrZCG71AkOzdTniLxrOgV3QmDYClJBw',
    appId: '1:312111156546:web:46ab1f29a9d2b4462b8cdb',
    messagingSenderId: '312111156546',
    projectId: 'fewwashproject',
    authDomain: 'fewwashproject.firebaseapp.com',
    storageBucket: 'fewwashproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCb7k79WSBHB2mQb-PKM_cjuAJC3ZoRUs',
    appId: '1:312111156546:android:1ae4eba675c784852b8cdb',
    messagingSenderId: '312111156546',
    projectId: 'fewwashproject',
    storageBucket: 'fewwashproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNoc0AoIyQndGLYC5ZypFMETsgaEF8qc',
    appId: '1:312111156546:ios:ac3463083b306cd22b8cdb',
    messagingSenderId: '312111156546',
    projectId: 'fewwashproject',
    storageBucket: 'fewwashproject.appspot.com',
    iosBundleId: 'com.msu.testdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNoc0AoIyQndGLYC5ZypFMETsgaEF8qc',
    appId: '1:312111156546:ios:ac3463083b306cd22b8cdb',
    messagingSenderId: '312111156546',
    projectId: 'fewwashproject',
    storageBucket: 'fewwashproject.appspot.com',
    iosBundleId: 'com.msu.testdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwBrZCG71AkOzdTniLxrOgV3QmDYClJBw',
    appId: '1:312111156546:web:69f46634f05e9c4e2b8cdb',
    messagingSenderId: '312111156546',
    projectId: 'fewwashproject',
    authDomain: 'fewwashproject.firebaseapp.com',
    storageBucket: 'fewwashproject.appspot.com',
  );
}
